<?xml version="3.0" encoding="UTF-8"?>

<simulation-properties version="2.0" application="asj-3.0.0" x="393" y="838" width="387" height="160">
  <property name="fishcount" value="5.0" input="true" output="true">
    <plotter enabled="true" min="0.0" max="100.0" window="Graphs" representing="fishcount" color="65280"/>
  </property>
  <property name="sealcount" value="4.0" input="true" output="true">
    <plotter enabled="true" min="0.0" max="100.0" window="Graphs" representing="sealcount" color="16711680"/>
  </property>
</simulation-properties>